### ISSUE TITLE
3월20일 문제

### ISSUE THREAD

**Issue by leejk0924** [boardLee/CodingTest#10]
## 오늘의 문제
- [ ] [프로그래머스]-[서울에서 김서방 찾기]-[https://school.programmers.co.kr/learn/courses/30/lessons/12919]
- [ ] [프로그래머스]-[중복된 숫자 개수]-[https://school.programmers.co.kr/learn/courses/30/lessons/120583]

## 비고
- 노트북 충전기를 잘 챙깁시다

**Comment by MHLEE12** [comment]
일부러 안챙긴건 아니지???????
