### ISSUE TITLE
230321 문제

### ISSUE THREAD

**Issue by leejk0924** [boardLee/CodingTest#13]
## 오늘의 문제
- [x] [프로그래머스]-[이진수 더하기]-[https://school.programmers.co.kr/learn/courses/30/lessons/120885]
- [ ] [프로그래머스]-[짝수는 싫어요]-[https://school.programmers.co.kr/learn/courses/30/lessons/120813]

## 비고
- 다짐이나 계획 등 작성

**Comment by MHLEE12** [comment]
ㅇㅈㄱ 점점 문제 안푼다
