### ISSUE TITLE
230328_오늘의 문제_JK

### ISSUE THREAD

**Issue by leejk0924** [boardLee/CodingTest#20]
## 오늘의 문제
- [x] [프로그래머스]-[연속된 수의 합]-[https://school.programmers.co.kr/learn/courses/30/lessons/120923]
- [x] [프로그래머스]-[문자열 뒤집기]-[https://school.programmers.co.kr/learn/courses/30/lessons/120822]

## 비고
- 잠시 휴식 후 다시 열공

**Comment by MHLEE12** [comment]
chickenJK
