### ISSUE TITLE
230315

### ISSUE THREAD

**Issue by leejk0924** [boardLee/CodingTest#5]
## 오늘의 문제
- [x] [프로그래머스]-[합성 수 찾기]-[https://school.programmers.co.kr/learn/courses/30/lessons/120846]
- [x] [프로그래머스]-[최빈값 구하기]-[https://school.programmers.co.kr/learn/courses/30/lessons/120812]
- [ ] [프로그래머스]-[짝수는 싫어요]-[https://school.programmers.co.kr/learn/courses/30/lessons/120813]

## 비고
- 이슈 까먹지말고 쓰자

**Comment by MHLEE12** [comment]
이슈 까먹지 마세요
